//! Single platform adapter for console key names.
use winit::{event::MouseButton, keyboard::KeyCode};

/// Physical sources with stock bind names.
pub(crate) enum Source {
    Key(KeyCode),
    Mouse(MouseButton),
    Wheel(bool),
}

/// Translate platform input without formatting, allocation, or layout-dependent names.
pub(crate) fn name(source: Source) -> Option<&'static str> {
    Some(match source {
        Source::Key(key) => match key {
            KeyCode::KeyA => "a",
            KeyCode::KeyB => "b",
            KeyCode::KeyC => "c",
            KeyCode::KeyD => "d",
            KeyCode::KeyE => "e",
            KeyCode::KeyF => "f",
            KeyCode::KeyG => "g",
            KeyCode::KeyH => "h",
            KeyCode::KeyI => "i",
            KeyCode::KeyJ => "j",
            KeyCode::KeyK => "k",
            KeyCode::KeyL => "l",
            KeyCode::KeyM => "m",
            KeyCode::KeyN => "n",
            KeyCode::KeyO => "o",
            KeyCode::KeyP => "p",
            KeyCode::KeyQ => "q",
            KeyCode::KeyR => "r",
            KeyCode::KeyS => "s",
            KeyCode::KeyT => "t",
            KeyCode::KeyU => "u",
            KeyCode::KeyV => "v",
            KeyCode::KeyW => "w",
            KeyCode::KeyX => "x",
            KeyCode::KeyY => "y",
            KeyCode::KeyZ => "z",
            KeyCode::Digit0 => "0",
            KeyCode::Digit1 => "1",
            KeyCode::Digit2 => "2",
            KeyCode::Digit3 => "3",
            KeyCode::Digit4 => "4",
            KeyCode::Digit5 => "5",
            KeyCode::Digit6 => "6",
            KeyCode::Digit7 => "7",
            KeyCode::Digit8 => "8",
            KeyCode::Digit9 => "9",
            KeyCode::ControlLeft => "CTRL",
            KeyCode::ControlRight => "CTRL",
            KeyCode::ShiftLeft => "SHIFT",
            KeyCode::ShiftRight => "SHIFT",
            KeyCode::AltLeft => "ALT",
            KeyCode::AltRight => "ALT",
            KeyCode::ArrowUp => "UPARROW",
            KeyCode::ArrowDown => "DOWNARROW",
            KeyCode::ArrowLeft => "LEFTARROW",
            KeyCode::ArrowRight => "RIGHTARROW",
            KeyCode::Insert => "INS",
            KeyCode::Delete => "DEL",
            KeyCode::PageUp => "PGUP",
            KeyCode::PageDown => "PGDN",
            KeyCode::Backquote => "`",
            KeyCode::BracketLeft => "[",
            KeyCode::BracketRight => "]",
            KeyCode::Backslash => "\\",
            KeyCode::IntlBackslash => "\\",
            KeyCode::Comma => ",",
            KeyCode::Period => ".",
            KeyCode::Slash => "/",
            KeyCode::Minus => "-",
            KeyCode::Equal => "=",
            KeyCode::Quote => "'",
            KeyCode::Semicolon => "SEMICOLON",
            KeyCode::NumLock => "KP_NUMLOCK",
            KeyCode::NumpadEnter => "KP_ENTER",
            KeyCode::NumpadAdd => "KP_PLUS",
            KeyCode::NumpadSubtract => "KP_MINUS",
            KeyCode::NumpadMultiply => "KP_STAR",
            KeyCode::NumpadDivide => "KP_SLASH",
            KeyCode::NumpadEqual => "KP_EQUALS",
            KeyCode::NumpadDecimal => "KP_DEL",
            KeyCode::Numpad0 => "KP_INS",
            KeyCode::Numpad1 => "KP_END",
            KeyCode::Numpad2 => "KP_DOWNARROW",
            KeyCode::Numpad3 => "KP_PGDN",
            KeyCode::Numpad4 => "KP_LEFTARROW",
            KeyCode::Numpad5 => "KP_5",
            KeyCode::Numpad6 => "KP_RIGHTARROW",
            KeyCode::Numpad7 => "KP_HOME",
            KeyCode::Numpad8 => "KP_UPARROW",
            KeyCode::Numpad9 => "KP_PGUP",
            KeyCode::Enter => "ENTER",
            KeyCode::Escape => "ESCAPE",
            KeyCode::Space => "SPACE",
            KeyCode::Backspace => "BACKSPACE",
            KeyCode::Tab => "TAB",
            KeyCode::CapsLock => "CAPSLOCK",
            KeyCode::Pause => "PAUSE",
            KeyCode::ScrollLock => "SCROLLLOCK",
            KeyCode::Home => "HOME",
            KeyCode::End => "END",
            KeyCode::F1 => "F1",
            KeyCode::F2 => "F2",
            KeyCode::F3 => "F3",
            KeyCode::F4 => "F4",
            KeyCode::F5 => "F5",
            KeyCode::F6 => "F6",
            KeyCode::F7 => "F7",
            KeyCode::F8 => "F8",
            KeyCode::F9 => "F9",
            KeyCode::F10 => "F10",
            KeyCode::F11 => "F11",
            KeyCode::F12 => "F12",
            _ => return None,
        },
        Source::Mouse(button) => match button {
            MouseButton::Left => "MOUSE1",
            MouseButton::Right => "MOUSE2",
            MouseButton::Middle => "MOUSE3",
            MouseButton::Back => "MOUSE4",
            MouseButton::Forward => "MOUSE5",
            _ => return None,
        },
        Source::Wheel(up) => {
            if up {
                "MWHEELUP"
            } else {
                "MWHEELDOWN"
            }
        }
    })
}
